/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KarnelerRouteImport } from './routes/karneler'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SinifClassIdRouteImport } from './routes/sinif.$classId'

const KarnelerRoute = KarnelerRouteImport.update({
  id: '/karneler',
  path: '/karneler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SinifClassIdRoute = SinifClassIdRouteImport.update({
  id: '/sinif/$classId',
  path: '/sinif/$classId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/karneler': typeof KarnelerRoute
  '/sinif/$classId': typeof SinifClassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/karneler': typeof KarnelerRoute
  '/sinif/$classId': typeof SinifClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/karneler': typeof KarnelerRoute
  '/sinif/$classId': typeof SinifClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/karneler' | '/sinif/$classId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/karneler' | '/sinif/$classId'
  id: '__root__' | '/' | '/karneler' | '/sinif/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KarnelerRoute: typeof KarnelerRoute
  SinifClassIdRoute: typeof SinifClassIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/karneler': {
      id: '/karneler'
      path: '/karneler'
      fullPath: '/karneler'
      preLoaderRoute: typeof KarnelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinif/$classId': {
      id: '/sinif/$classId'
      path: '/sinif/$classId'
      fullPath: '/sinif/$classId'
      preLoaderRoute: typeof SinifClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KarnelerRoute: KarnelerRoute,
  SinifClassIdRoute: SinifClassIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
